name: refresh-data

on:
  schedule:
    - cron: '*/30 00-01 * * *'
  push:
    branches:
      - master
      - main

jobs:
  refresh-data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("remotes", "pkgload", "rmarkdown", "usethis"), type = "binary")'
      - name: Install dependencies
        run: Rscript -e 'remotes::install_deps(type = "binary", force = FALSE, dependencies = TRUE)'
      - name: Get data
        run: Rscript -e 'source(here::here("data-raw", "refresh_data.R"), echo = TRUE)'
      - name: Render README
        run: Rscript -e 'rmarkdown::render(here::here("README.Rmd"))'
      - name: Commit
        run: |
          git config --global user.name 'Matt Cowgill'
          git config --global user.email 'mattcowgill@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
